version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: tasklar-db-1
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mysql_data:
