# Generated by Django 5.0.6 on 2024-07-24 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumer', '0001_initial'),
        ('service', '0001_initial'),
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.IntegerField()),
                ('punctuality_score', models.IntegerField()),
                ('communication_score', models.IntegerField()),
                ('description', models.TextField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer.consumer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('tasker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.tasker')),
            ],
        ),
    ]
