# Generated by Django 5.0.1 on 2024-07-10 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_city_user_name_user_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('T', 'Tasker'), ('C', 'Consumer')], default='C', max_length=1),
        ),
    ]
