# Generated by Django 5.0.1 on 2024-07-10 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=255)),
                ('days_of_week', models.CharField(help_text='Dias da semana em que o serviço está disponível. Exemplo: "0123456"', max_length=7)),
                ('start_time', models.TimeField(help_text='Horário de início de atendimento')),
                ('end_time', models.TimeField(help_text='Horário de fim de atendimento')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.category')),
                ('tasker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.tasker')),
            ],
        ),
    ]
